### ISSUE TITLE
Toolbar Header

### ISSUE THREAD

**Issue by SybelBlue** [SybelBlue/codesign-genie#18]
It's becoming clear we need a toolbar header. In all likelihood it will be `flex`y and `sticky`, maybe even `transparent` if we're lucky.

It's gotta hold:
- Change Theme
- Change Deck
- Sort
- Timeline Open

... and any other tool we need (I'm thinkin' zoom and such).

**Comment by go-bears** [comment]
changes on branch `add-toolbar`

11/5:
change theme, change deck, sort moved to tool bar.
